*** Variables ***

${TAB_EXPLORA}    //android.view.View[contains(@content-desc, "Explora\nPestaña 2 de 5")]
${TITLE_EXPLORA}  //android.view.View[@content-desc="Explorar"]
${BODY_EXPLORA}   //android.view.View[@content-desc="Nutrición Transforma tu día a día con ideas y recetas para una alimentación sana y balanceada. Revive nuestras Charlas Salud Mental Consejos prácticos para mejorar tu bienestar emocional y reducir el estrés en tu vida diaria."]
${SEARCH_BAR}    //android.view.View[@content-desc="Explora y aprende..."]
${QUESTION_ANSWERS}    //android.view.View[@content-desc="Preguntas y respuestas"]
${SEE_MORE_BUTTON}     (//android.view.View[contains(@content-desc,"VER MÁS")])[1]
${MENTAL_HEALTH}    //android.widget.ImageView[@content-desc="Salud Mental"]
${NUTRITION}        //android.widget.ImageView[@content-desc="Nutrición"]
${RELATIONS}        //android.widget.ImageView[@content-desc="Relaciones"]
${TRAINING}    //android.widget.ImageView[@content-desc="Entrenamiento"]
${PETS}    //android.widget.ImageView[@content-desc="Mascotas"]
${BACK_WINDOW}    //android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View[1]
${TITLE_HEALTH}  //android.view.View[@content-desc="Salud Mental"]
${TITLE2_HEALTH}    //android.view.View[@content-desc="🌟 Recomendado"]
${TITLE_NUTRITION}  //android.view.View[@content-desc="Nutrición"]
${BODY_NUTRITION}    //android.view.View[@content-desc="Transforma tu día a día con ideas y recetas para una alimentación sana y balanceada."]
${TITLE2_NUTRITION}    //android.view.View[@content-desc="🌟 Recomendado"]
${TITLE_RELATIONS}    //android.view.View[@content-desc="Relaciones"]
${BODY_RELATIONS}    //android.view.View[@content-desc="Fortalece tus vínculos con estrategias para conexiones más profundas y significativas."]
${TITLE2_RELATIONS}    //android.view.View[@content-desc="🌟 Recomendado"]
${TITLE_TRAINING}    //android.view.View[@content-desc="Entrenamiento"]
${BODY_TRAINING}    //android.view.View[@content-desc="Activa tu energía diaria cuerpo y mente en sintonía para un estilo de vida saludable."]
${TITLE2_TRAINING}    //android.view.View[@content-desc="🌟 Recomendado"]
${TITLE_PETS}   //android.view.View[@content-desc="Mascotas"]
${BODY_PETS}    //android.view.View[@content-desc="Cuida y entiende mejor a tus mascotas, dales lo mejor para una vida feliz y saludable."]
${TITLE2_PETS}    //android.view.View[@content-desc="🌟 Recomendado"]
${BANNER_HEALTH}     //android.widget.ImageView[@content-desc="ACTUALIZA TU PERFIL DE SALUD"]
${CLOSE_WINDOW1}     //android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View
${SECTION_EXPLORA}     xpath=(//android.view.View[contains(@content-desc, "Video")])[1]
${BUTTON_CLOSE}      //android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]


